### ISSUE TITLE
Implement custom validation checks:

### ISSUE THREAD

**Issue by jkupferer** [redhat-gpte-devopsautomation/resource-claim-operator#16]
Custom validation checks should process using jinja2 to validate check conditions:
```
spec:
  validation:
    customValidation:
    - name: destroy schedule must be no more than 14 days from creation
      check: spec.actionSchedule.destroy < timestamp(resource_claim.metadata.creationTimestamp).add('14d')
    - name: stop schedule must be no more than 8 hours from now
      check: spec.actionSchedule.stop < timestamp.utcnow.add('8h')
```
